# Generated by Django 5.1.5 on 2025-03-28 23:19

import accounts.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='uuid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', accounts.models.EVMAddressField(max_length=42, unique=True, verbose_name='address')),
                ('username', models.CharField(blank=True, max_length=200, unique=True, verbose_name='username')),
                ('profile_picture_url', models.URLField(blank=True, default='', max_length=500, validators=[django.core.validators.URLValidator()], verbose_name='profile_picture_url')),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
